# document: https://github.com/realm/SwiftLint
disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - identifier_name
  - cyclomatic_complexity
  - large_tuple
  - function_parameter_count
  - nesting
  - redundant_string_enum_value   # Codableの適合性で利用されるため、明示的にしたい

opt_in_rules:
  - implicit_return # implicit returnを推奨
  - sorted_imports # importをsortする
  - array_init # Array()を推奨
  - conditional_returns_on_newline
  - empty_string # 同上
  - explicit_init # explicitに.initを書かない
  - first_where # .filter { }.firstよりも.first(where:)を用いる．
  - operator_usage_whitespace # 演算子の左右に空白を
  - redundant_nil_coalescing # ?? nilを禁止
  - reduce_into # reduce(into:)を推奨
  - toggle_bool # .toggleを推奨

analyzer_rules:
  - unused_declaration
  - unused_import

included:
  - MainApp
  - Keyboard
  - Shared
  - azooKeyTests
  - AzooKeyCore
  - DictionaryDebugger
excluded:
  - AzooKeyCore/.build
type_name:
  excluded: 
    - ID
    - 行
  max_length: 100
trailing_comma:
  mandatory_comma: true
