name: Build on push

on: push

jobs:
  build:
    name: Build
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Project
        run: |
          xcodebuild build -project azooKey.xcodeproj \
                     -scheme MainApp \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO
